version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    restart: always

  client:
    build: ./client
    ports:
      - "5173:5173"  
    env_file:
      - ./client/.env
    restart: always

  admin:
    build: ./admin
    ports:
      - "5174:5174"  
    env_file:
      - ./admin/.env
    restart: always